server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:8220/openemr
    username: root
    password: root
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true